project:
  type: book
  output-dir: _site

book:
  title: "Uni-Saarland Survival Guide"
  author: "Zichao Wei"
  date: "2024/5/8"
  chapters:
    - index.qmd

format:
  html:
    theme: cosmo
    toc: true
