project:
  type: book
  output-dir: _site

book:
  title: "Uni-Saarland Survival Guide"
  author: "Zichao Wei"
  date: "2024/5/8"
  chapters:
    - index.qmd
  navbar:
    background: primary
    right:
      - icon: globe
        menu:
          - text: English
            href: https://academic.exusiaiwei.top/uni-saarland-survival-guide/en/
          - text: 中文
            href: https://academic.exusiaiwei.top/uni-saarland-survival-guide/zh/

format:
  html:
    theme: journal
    code-copy: true
    toc: true
