project:
  type: book
  output-dir: _site

book:
  title: "萨尔大学生存指南"
  reader-mode: true
  author: "魏子超"
  chapters:
    - 主页.qmd
    # Consider adding parts for better structure if chapters increase
    - 应急联络与电话.qmd
    - part: "准备篇"
      chapters:
        - 住宿.qmd
    - 参考文献.qmd
  bread-crumbs: true
  favicon: https://www.uni-saarland.de/typo3conf/ext/uni_saarland/Resources/Public/Images/logo_uni_saarland.svg
  repo-url: https://github.com/exusiaiwei/uni-saarland-survival-guide
  repo-actions: [edit, issue]
  search: true
  page-navigation: true # 添加页面导航
  sidebar:
    style: docked
    background: light
  navbar:
    background: primary
    right:
      - icon: translate
        menu:
          - text: English
            href: https://exusiaiwei.github.io/uni-saarland-survival-guide/en/
          - text: 中文
            href: https://exusiaiwei.github.io/uni-saarland-survival-guide/zh/
  comments:
    giscus:
      repo: exusiaiwei/uni-saarland-survival-guide # 你的仓库
      repo-id: "R_kgDOL40BXQ"              # 从 Giscus 页面复制
      category: comment                # 你选定的分类名 (确保是 Announcement 类型)
      category-id: "DIC_kwDOL40BXc4CpT7Q"         # 从 Giscus 页面复制
      mapping: pathname
      reactions-enabled: true
      input-position: top
      theme: preferred_color_scheme    # 或 light / dark
      loading: lazy

bibliography: ../assets/bibliography.bib

format:
  html:
    theme:
      - cosmo
      - guide_style.scss
    code-copy: true
    code-fold: true  # 允许折叠代码块
    toc: true
    lang: zh


jupyter:
  kernelspec:
    name: python3
    display_name: Python 3
    language: python