project:
  type: book
  output-dir: _site

book:
  title: "萨尔大学生存指南"
  reader-mode: true
  page-footer:
    left: |
      创作团队：在彼扬水，Zorzaneczka，Joakim，就不喜欢吃mensa
    right: |
      使用<a href="https://quarto.org/">Quarto</a>构建
  cover-image: LST.png
  chapters:
    - index.qmd
    # Consider adding parts for better structure if chapters increase
    - 应急联络与电话.qmd
    - part: "出发前须知"
      chapters:
        - 住宿.qmd
        - 落地交通.qmd
        - 核对清单与注意事项.qmd
        - 护照与签证申请.qmd
    - part: "生活"
      chapters:
        - 就医、药品与健康.qmd
        - 交通.qmd
        - 电讯指南.qmd
        - 经济与金融.qmd
        - 医疗保险细化指南.qmd
        - 食品进阶需求.qmd
    - part: "学校事务"
      chapters:
        - 校园卡.qmd

    - part: "行政"
      chapters:
        - 延签、落户与外管局.qmd
        - 税号.qmd
        - 邮政.qmd
        - 护照丢失.qmd
        - 广播电视费.qmd
    - 参考文献.qmd
  favicon: https://www.uni-saarland.de/typo3conf/ext/uni_saarland/Resources/Public/Images/logo_uni_saarland.svg
  repo-url: https://github.com/exusiaiwei/uni-saarland-survival-guide
  repo-actions: [edit, issue]
  search: true
  page-navigation: true # 添加页面导航
  sidebar:
    style: floating
  comments:
    giscus:
      repo: exusiaiwei/uni-saarland-survival-guide # 你的仓库
      repo-id: "R_kgDOL40BXQ"              # 从 Giscus 页面复制
      category: comment                # 你选定的分类名 (确保是 Announcement 类型)
      category-id: "DIC_kwDOL40BXc4CpT7Q"         # 从 Giscus 页面复制
      mapping: pathname
      reactions-enabled: true
      input-position: top
      theme: preferred_color_scheme    # 或 light / dark
      loading: lazy

bibliography: ../assets/bibliography.bib

format:
  html:
  # 新增部分开始
    include-after-body:
      text: |
        <script>
          // 允许内联脚本的安全策略
          document.addEventListener('DOMContentLoaded', function() {
            if (window.trustedTypes && trustedTypes.createPolicy) {
              trustedTypes.createPolicy('default', {
                createHTML: (string) => string,
                createScript: (string) => string
              });
            }
          });
        </script>
    #新增部分结束
    theme:
      - cosmo
      - guide_style.scss
    code-copy: true
    code-fold: true  # 允许折叠代码块
    toc: true
    lang: zh

    author-meta: "在彼扬水，Zorzaneczka，Joakim；就不喜欢吃mensa"
    callout-appearance: simple

jupyter:
  kernelspec:
    name: python3
    display_name: Python 3
    language: python