project:
  type: book
  output-dir: _site

book:
  title: "萨尔大学生存指南"
  author: "魏子超"
  date: "2024/5/8"
  chapters:
    - index.qmd
  favicon: https://www.uni-saarland.de/typo3conf/ext/uni_saarland/Resources/Public/Images/logo_uni_saarland.svg
  cover-image: https://www.uni-saarland.de/typo3conf/ext/uni_saarland/Resources/Public/Images/logo_uni_saarland.svg
  repo-url: https://github.com/exusiaiwei/uni-saarland-survival-guide
  repo-actions: [edit]
  search: true
  sidebar:
    style: docked
    background: light
  navbar:
    background: primary
    right:
      - icon: globe
        menu:
          - text: English
            href: https://academic.exusiaiwei.top/uni-saarland-survival-guide/en/
          - text: 中文
            href: https://academic.exusiaiwei.top/uni-saarland-survival-guide/zh/

format:
  html:
    theme: journal
    code-copy: true
    toc: true
