# 前言 {.unnumbered}

欢迎大家打开这本《萨尔大学生存指南》！

讲真，作为一名刚刚收到offer的萨尔大学新生，在为即将到来的留学生活而激动的同时，我也感受到了对未来的紧张和不安。毕竟，从繁杂的程序到陌生的环境再到学业的压力，留学生活中的挑战可谓是层出不穷。要解决这些问题需要查询大量的信息，进行大量的准备，而这些信息又分散在各个网站，各个帖子里，甚至很多经历只能依靠口口相传。可以说，我们急需一份一站式的指南，来帮助我们应对即将到来的挑战。

幸运的是，已经有了一些类似的工作，例如Saarbrücken starter pack。这本书也是受到了这些工作的启发。在此基础上，我希望这本书的交互式电子书设计能够更加方便大家进行信息检索。

此外，本书是由Quarto框架制作的，其源代码托管在GitHub上，并使用Github Pages构建了多语言的网页版本。如果你有任何关于本书的建议或者想要为本书贡献内容（包括翻译），你可以通过提交Issue和Pull Request来实现。

如果你是萨尔大学的在校生或校友,如果你有任何关于学习、生活、娱乐等方面的宝贵经验和建议；或者你想为本书贡献更多语言版本的翻译，都可以联系我。

希望能在萨尔大学的生活中遇到你！

一个正在紧张准备行李的萨尔大学新生~

# 阅前须知 {.unnumbered}
1. 本指南信息来源多样，经过且只经过笔者与部分同学的认可，但并不能100%确保信息准确且实时更新，因此建议您自行确认其中可能潜在的不确定性和出错的可能性，并尽可能在（尤其是价格和规定）方面做好冗余打算。
2. 本生存指南为非盈利性项目，因此将不主动指名各种私人店铺或刊登商业广告信息。本指南的初衷是希望您能够通过基础信息帮助您自主解决问题
3. 本指南已经尽可能设身处地地思考您可能会遇到的困惑，若依然有未覆盖到的部分，作者团队向您表示诚挚的歉意。在此情况下烦请您能够向作者团队反馈，以便作者团队能够及时更新。并且萨尔学生会欢迎您在任何官方组织的微信群组中发送您的问题。
4. 请您注意，大群中虽然多数为学生，也有部分未知职业立场的成员。因此您涉及到经济/利益方面的提问请谨慎筛查信息源，防止黑中介诈骗。已有多个案例且受害人数量不少。若您获得了让您初步满意的答案，请考虑向积极回复的同学表示必要的感谢，萨尔生存团队成员向您表示真诚的感谢。
5. 如果您对本文还有另外的想法和疑问希望私下讨论或有任何相关的私人话题希望获得初步建议，也非常欢迎您发送Github Issues或点击“反馈问题”按钮。
   
::: {.callout-tip}

# 注意

本提示框将用于注释一些制作团队的个人经验以及部分冷门小知识
:::
