# 住宿

```{python}
#| echo: false
import folium
from folium.features import CustomIcon

# 宿舍的信息
dormitories = [
    {"name": "Wohnheime E", "location": (49.257400, 7.041500), "type": "university", "color": "darkblue", "icon": "university"},
    {"name": "Studentenwohnanlage Waldhaus", "location": (49.244890, 7.021330), "type": "university", "color": "darkblue", "icon": "university"},
    {"name": "Studentenwohnheim Guckelsberg", "location": (49.265390, 7.040530), "type": "university", "color": "darkblue", "icon": "university"},
    {"name": "Studentenwohnheim Rotenberg", "location": (49.235740, 7.001840), "type": "university", "color": "darkblue", "icon": "university"},
    {"name": "TILSITER STRASSE", "location": (49.23601787263703, 7.048907284661837), "type": "private", "color": "cadetblue", "icon": "building"},
    {"name": "Carl Duisberg Haus", "location": (49.23835064843005, 7.036376055826561), "type": "private", "color": "cadetblue", "icon": "building"},
    {"name": "ESG Saarbrücken", "location": (49.24468732847097, 7.018832677740648), "type": "other", "color": "cadetblue", "icon": "building"},
    {"name": "Cusanushaus Saarbrücken", "location": (49.2356132668547, 6.990818476723417), "type": "other", "color": "cadetblue", "icon": "building"},
    {"name": "CAMPO NOVO Saarbrücken", "location": (49.24218686964247, 7.007729411047266), "type": "private", "color": "cadetblue", "icon": "building"},
    {"name": "Quint Immobilien GmbH", "location": (49.27712239030715, 7.034571602702453), "type": "private", "color": "cadetblue", "icon": "building"},
    {"name": "Zymma", "location": (49.231796028851136, 7.006448137049002), "type": "other", "color": "cadetblue", "icon": "building"},
    {"name": "WOGE Saar", "location": (49.23176489619987, 6.999792006811255), "type": "other", "color": "cadetblue", "icon": "building"},
    {"name": "Study Cubes", "location": (49.231460, 6.973284), "type": "private", "color": "darkblue", "icon": "building"}
]

# 学校的坐标
school_location = (49.2554, 7.0419)

# 创建地图,以学校的坐标为中心
map = folium.Map(location=school_location, zoom_start=12)

# 添加标记
for dormitory in dormitories:
    icon = folium.Icon(color=dormitory["color"], icon=dormitory["icon"], prefix='fa')
    folium.Marker(
        location=dormitory["location"],
        popup=folium.Popup(html=dormitory["name"], max_width=200),
        tooltip='Click for more information',
        icon=icon
    ).add_to(map)

# 显示地图
map
```


## 住房列表
@tbl-overview 提供了一个概览。

| 宿舍名称 | 类型 | 房型 | 月租金范围 |
|----------|------|------|------------|
| Studentenwohnheim E（学生宿舍E） | 学校宿舍 | 单人公寓 (72间) | 370€,包括水电暖 |
| Studentenwohnheim Waldhaus（瓦尔德豪斯学生宿舍） | 学校宿舍 | 单人公寓 (254间), 双人间 (17间), 家庭公寓 (14间) | 309€ - 885€ |
| Studentenwohnheim Guckelsberg（古克尔斯贝格学生宿舍） | 学校宿舍 | 单人公寓 (46间), 双人公寓 (66间), 家庭公寓 (2间) | 252€ - 750€ |
| Studentenwohnheim Rotenberg（罗滕贝格学生宿舍） | 学校宿舍 | 单人公寓 (45间), 双人间 (5间), 三人间 (1间) | 275€ - 357€ |
| TILSITER STRASSE 蒂尔西特大街合租公寓 | 私人宿舍 | 单人间 | 310€ - 400€ |
| CARL-DUISBERG-HAUS 卡尔·杜伊斯堡豪斯 | 私人宿舍 | 单人间, 单间公寓 | 400€ - 430€ |
| ESG-WOHNHEIM ESG学生公寓 | 私人宿舍 | 单人间, 双人间 | 277€ - 466€ |
| CUSANUSHAUS 库萨努斯之家 | 私人宿舍 | A类单人间, B类单人间, C类单间公寓 | 290€ - 410€ |
| CAMPO NOVO | 私人宿舍 | 单人间(学生), 两房(学生), 两房(学生合租), 两房(商务), 两房复式(商务) | 545€ - 1160€ |
| Quint Immobilien | 私人宿舍 | - | - |
| Zymma | 私人宿舍 | - | - |
| WOGE Saar | 私人宿舍 | - | - |
| Studioeins | 私人宿舍 | 单人间 | - |
| Study Cubes | 私人宿舍 | 单人间, 双人间 | 268€-300€（单人），661€-701€（双人）不包电网 |
: 萨尔大学学生宿舍概览 {#tbl-overview}


### 大学管理的学生公寓 {#tbl-dormitory}

萨尔大学管理的学生宿舍主要有四个,分别是:

- [Studentenwohnheim E（学生宿舍E）](#tbl-wohnheim-e)
- [Studentenwohnheim Waldhaus（瓦尔德豪斯学生宿舍）](#tbl-waldhaus)
- [Studentenwohnheim Guckelsberg（古克尔斯贝格学生宿舍）](#tbl-guckelsberg)
- [Studentenwohnheim Rotenberg（罗滕贝格学生宿舍）](#tbl-rotenberg)


有关每个宿舍的更多详情,请参见:

- [Studentenwohnheim E（学生宿舍E）](#tbl-wohnheim-e) ([官网](https://www.stw-saarland.de/de/Wohnen/Wohnheime-in-Saarbrucken/Studentenwohnheim-E))
- [Studentenwohnheim Waldhaus（瓦尔德豪斯学生宿舍）](#tbl-waldhaus) ([官网](https://www.stw-saarland.de/de/Wohnen/Wohnheime-in-Saarbrucken/Studentenwohnheim-Waldhaus))
- [Studentenwohnheim Guckelsberg（古克尔斯贝格学生宿舍）](#tbl-guckelsberg) ([官网](https://www.stw-saarland.de/de/Wohnen/Wohnheime-in-Saarbrucken/Studentenwohnheim-Guckelsberg))
- [Studentenwohnheim Rotenberg（罗滕贝格学生宿舍）](#tbl-rotenberg) ([官网](https://www.stw-saarland.de/de/Wohnen/Wohnheime-in-Saarbrucken/Studentenwohnheim-Rotenbergstrasse))


在线申请地址：https://tl1host.eu/SWSB/#home



#### Studentenwohnheim E（学生宿舍E） {#tbl-wohnheim-e}

- 房型：单人公寓 (72间)
- 面积：约20m²
- 设施：衣柜、沙发床、床头柜、书架、桌椅、迷你厨房、小浴室(淋浴、马桶、洗脸池)。每层楼的走廊都设有一个公共区域，地下室则设有带电视的休闲室和室外自行车停放处。
- 租金：370€,包括水电暖
- 位置：校园内，靠近食堂。
- 地址：Campus Saarbrücken Gebäude D 4.5 66123 Saarbrücken

#### Studentenwohnheim Waldhaus（瓦尔德豪斯学生宿舍） {#tbl-waldhaus}

- 房型：单人公寓 (254间), 双人间 (17间), 家庭公寓 (14间)
- 面积：单人公寓16m², 双人间32m², 家庭公寓40m² / 80m²
- 设施：衣柜、沙发床、床头柜、书架、桌椅、迷你厨房、小浴室(淋浴、马桶、洗脸池)。地下室设有多个社区空间：电视室、乒乓球室、健身房、小组工作间、家庭酒吧、自行车库、三部电梯
- 租金：
  - 单人公寓: 335€
  - 合租公寓单间（11 平方米）：309€
  - 合租公寓单间（16 平方米）：356€
  - 家庭公寓（40 平方米）：685€
  - 家庭公寓（80 平方米）：885€
- 位置：位于萨尔布吕肯市中心与校园之间。
- 地址：Waldhausweg 15-21 66123 Saarbrücken

#### Studentenwohnheim Guckelsberg（古克尔斯贝格学生宿舍） {#tbl-guckelsberg}

- 房型：单人公寓 (46间), 双人公寓 (66间), 家庭公寓 (2间)
- 面积：单人公寓19-35m², 双人公寓29-38m², 家庭公寓57m²
- 设施：衣柜、沙发床、床头柜、书架、桌椅、迷你厨房、小浴室(淋浴、马桶、洗脸池)
- 租金：
  - 单人公寓: 306€ - 366€
  - 合租公寓单间（11 平方米）：252€
  - 合租公寓单间（14 平方米）：337€
  - 合租公寓单间（16 平方米）：274€ - 280€
  - 家庭公寓：750€
- 位置：位于杜德维尔，紧邻城市森林。
- 地址：Richard-Wagner-Straße 91 66125 Saarbrücken-Dudweiler

#### Studentenwohnheim Rotenberg（罗滕贝格学生宿舍） {#tbl-rotenberg}

| 房型 | 面积 | 设施 | 租金 |
|------|------|------|------|
| 单人公寓 (45间) | 21-27m² | 衣柜、沙发床、床头柜、书架、桌椅、迷你厨房、小浴室(淋浴、马桶、洗脸池) | 324€ - 357€ |
| 双人间 (5间) | 34m² | 同上,共用厨房和浴室 | 275€ |
| 三人间 (1间) | 56m² | 完全配备,共用厨房和浴室 | 275€ - 289€ |

- 房型：单人公寓 (45间), 双人间 (5间), 三人间 (1间)
- 面积：单人公寓21-27m², 双人间34m², 三人间56m²
- 设施：衣柜、沙发床、床头柜、书架、桌椅、迷你厨房、小浴室(淋浴、马桶、洗脸池)
- 租金：
  - 单人公寓: 342€ - 377€
  - 双人合租单间: 290€
  - 三人合租单间: 290€ - 304€
- 位置：距离学校5公里，靠近市中心。
- 地址：Rotenbergstraße 12-14 66111 Saarbrücken


> **目前学生宿舍没有空房！**
>
> Derzeit sind keine freien Zimmer in den Wohnheimen verfügbar!
>
> ——Wohnen im Wohnheim



### 私人运营的学生公寓

| 名称 | 房型 | 面积 (m²) | 月租金 (€) | 押金 (€) | 设施 |
|---|---|---|---|---|---|
| [TILSITER STRASSE 蒂尔西特大街合租公寓](https://www.sib-saarbruecken.de/wohnen/wohngemeinschaften/wohngemeinschaften_tilsiter_strasse) | 单人间 | 14 / 23 | 310 / 400 (含管理费) | 480 / 600 (一次性) | 共用厨房和卫浴,全家具 |
| [CARL-DUISBERG-HAUS 卡尔·杜伊斯堡豪斯](https://www.sib-saarbruecken.de/wohnen/wohngemeinschaften/studentenwohnen_im_carl_duisberg_haus) | 单人间 / 单间公寓 | - | 400 / 430 (含电费) | 600 / 690 | 共用厨房 / 小厨房,独立卫浴,全家具 |
| [ESG-WOHNHEIM ESG学生公寓](http://www.waldhausweg7.de/) | 单人间 / 双人间 | - | 277-466 (含管理费和网络) | - | 共用厨房和卫浴,每层8个房间 |
| [CUSANUSHAUS 库萨努斯之家](http://www.cusanustreff.de/) | A类单人间 / B类单人间 / C类单间公寓 | 12 / 23 / 31 | 290-320 / 350 / 390-410 | - | A: 共用厨房和卫浴; B: 小厨房,共用卫浴; C: 小厨房,独立卫浴;全家具 |
| [CAMPO NOVO](https://www.campo-novo-saarbruecken.de/) | 单人间(学生) / 两房(学生) / 两房(学生合租) / 两房(商务) / 两房复式(商务) | 20-26 / 44-45 / 44-46 / 43-52 / 53-61 | 615-690 / 990 / 545 / 990-1160 / 1160 (含管理费) | - | 独立厨房卫浴,阳台或露台,全家具,健身房,洗衣房,社区花园,地下车库 |
| [Quint Immobilien](https://www.quint-immobilien.de/) | - | - | - | - | 目前已租满 |
| [Zymma](https://zymma.de/listings/?start=01.04.2023&location=4) | - | - | - | - | 目前已租满,可申请候补 |
| [WOGE Saar](https://www.freundlich-wohnen.de/service/wohnraum-fuer-studenten/) | - | - | - | 1个月租金 | 学生优惠政策:减免押金和缩短租期 |
| [Studioeins](http://www.studioeins.info/) | 单人间 | 23-42 | - | - | 市中心,独立厨房卫浴,可选家具 |

注:

1. "-"表示信息未提供
2. Quint Immobilien和Zymma目前房源已租满
3. WOGE Saar主要提供面向学生的优惠政策,具体房型和价格未给出
4. Studioeins可选家具,价格未给出
5. Saarländischen Bauträgers(SBT)的网页无法打开,暂无信息

### 私人住宅
