# 长短途交通 {.unnumbered}

本章节为准备篇中的落地交通的扩展说明页面，可以将两部分内容结合起来一起参考。

## 火车
**DB Fahrplan, Auskunft, Tickets, informieren und buchen - Deutsche Bahn**
德国火车晚点情况严重，因此个人建议选择线路时不要考虑转车时间少于15分钟的线路。
德国火车车票参与市场竞争，因此票价波动趋势可以参考机票。如果您有旅行需求，请提早至少3周考虑购买车票，并考虑一并购入返程票。

### 德国票
截至2025年4月18日，德国票依然包含在学期票内。
该票为全德国低速车通用票，包含：

- 德国境内的所有低速火车（RE/RB/S/IRC）
- 任何地区的公交/轻轨系统

**注意**：请养成在出发前检查德铁App中对您所需要乘坐火车的额外信息描述，不能排除您的行程中可能出现的某一辆车无法被德国票覆盖的可能性。

### 激活流程
1. 请前往 [saarVV官网](https://saarvv.de/)
   - 请确认您已经成功注册了一个saarvv有效个人账户，并使用您的常用邮箱。
2. 寻找 **Deutschlandsemester ticket** 选项。
3. 点击 **zum Bestellprozess** 按钮。
4. 选择您的学校组织。
5. 登录您的学校账号密码。
6. 选择您的注册有效期。
7. 进入您的个人信息页完善并核对邮箱信息。
8. 确认并提交申请。
9. 前往您的邮箱确认是否收到“确认函”。
10. 学期票通常会在几个工作日后推送至您的手机。
11. 在您第六步选择的有效期内，每月末几天将自动推送下个月的票至您的账户。
    - 若发现缺失票，建议重新登录saarvv个人账号并重启应用程序。
12. 在 **左上角三条横线 --> Tickets/Accounts** 中查看。

### 购买流程
- 若您无法通过学校渠道获得德国票或有家人来拜访您，请考虑购买德国票。
- 由于该德国票全国通用，因此您从任意一个交通公司购买均无区别。
- **个人建议**：出于消费者保护的目的，建议向德国铁路总台或saarVV购买。

## 火车类型
- **ICE/IC/EC（快速车）**：运行速度快且停靠站少，价格稍高。
- **RE/RB/S/IRC（慢速车）**
  - **RE/RB**：区域快/区域普速，规模庞大，线路选择多。
  - **S**：跨区轻轨，线路长，晚点可能性高，停靠站多。
  - **IRC**：区域性运行的长线列车。

### FlixTrain
一类私营公司的火车，该运营系统与德铁独立，因此如果您的线路中包含该公司火车，请单独购票。

## 其他交通方式
### 大巴
- **前往卢森堡的直达大巴 Saarbrücken Express - CFL | Emile Weber**
  - 您的学生卡在经过每个学期的打印更新后，有权免费乘坐该线路。
  - 耗时约1小时30分钟 - 1小时45分钟，视交通而定。
  - **注意**：请携带护照和居留证。
- **FlixBus**
  - 由私营公司运营的点对点大巴，部分线路价格较低且时间与火车相近。
  - 请检查车票价格和线路。
  - **不建议乘坐任何黑大巴**。

### 飞机
- 萨尔布吕肯机场规模较小，起降航司较少，同时目的地受限。
- 如需出行，可以考虑附近机场
  - 卢森堡机场：距离近，可以免费乘坐大巴抵达卢森堡市区（见上），再换乘卢森堡免费公交抵达机场，总用时约2-2.5小时。卢森堡航线较丰富，常见廉价航空目的地包括英国伦敦，意大利米兰，葡萄牙里斯本和波尔图，法国马赛、尼斯等等。欧洲主要城市与卢森堡也有直达航班。其他度假目的地包括但不限于突尼斯，佛得角，希腊等等。
  - 法兰克福FRA机场：德国航空枢纽，无需多言。
  - 法兰克福Hahn机场：请在搜索廉价机票时不要被此机场迷惑。该机场有非常多廉价航空航线，但并不位于法兰克福附近。虽距离萨尔布吕肯直线距离较近，但搭乘公交前往十分费时费力。您也可以先坐RE3前往美因茨，再购买单独的机场大巴。如果您不缺时间又想省钱，可以考虑从此机场出发。
- 更远一些的机场包括：科隆波恩机场，卡鲁-巴登巴登机场，斯图加特机场。

### 汽车/计程车
- 计程车价格昂贵，且需电话叫车（出租车停靠点除外，例如主火门口）。
- 持有中国驾照的留学生可在德国租车，但仅限短期使用（最多6个月）。
- 之后需申请德国驾照，需通过理论考试及路考。
- **具体政策请密切关注官方通告**。

### 自行车
- 本市路况稍微复杂，伴有较多的上下坡。
- 若您考虑购买自行车，请选择变速自行车，并按规定：
  - 上牌
  - 安装前后车灯
  - 佩戴头盔

### 公共交通
- 本市公交网发达，可满足基础出行需求。
- 由于交通受车流量影响较大，请仅将App所示班次表作为参考，并安排冗余时间以防误程。
- 本市仅有一条轻轨线路，无地铁线路。
- **轻轨信息**：
  - 轻轨线路横穿本市，并可抵达法国小镇 **Sarreguemines**。
  - 该段行程包含在您的德国票中。
  - **注意**：请携带护照和居留证。