# 就医、药品与健康需求

首先编者团队对您身体抱恙表示慰问和祝福，祝您早日康复

德国的就医系统较为复杂并且和国内的体系有一定的区别，并可能有相当的概率踢皮球，因此希望您在日常生活中多多注意个人健康

德国的几乎所有诊所都实行预约制，您需要在就诊前和您的目标诊所通过电话，邮件（不推荐）或通过医保公司/在线预约服务等途径预约Termin。否则您可能会被拒诊或陷入长时间等待的情况。

::: {.callout-tip}
# 注意！

德国的诊所（Praxis）和医院（Klinik/Krankenhaus）拥有本质区别。您无法在医院获得普通的门诊服务。因此若您身体抱恙，请不要联系医院，请联系诊所
:::

## 医疗保险

德国强制各位购买医疗保险，并且作为大学生，笔者团队建议您购买公立医疗保险。公立医疗保险通常没有什么大的福利区别，仅可能在返利方面/额外福利方面有差别。因此如果您暂时没有什么好想法，可以选择

1. 您家附近最近的医保公司总部是哪个医保，就选择该医保（出于寻找客服服务便捷性考虑）
2. 如果您有熟人，该公立医保公司有推荐福利，您可以和朋友共享（出于薅羊毛考虑）

若您由于年龄问题或经济条件问题导致您不得不考虑放弃公立保险的服务，您需要和大学协商并签署自愿放弃公立医保协议，随后尽可能寻找覆盖面的私立医保公司。但是出于覆盖面和报销复杂程度和对就医和开药方面的考虑，笔者团队强烈建议您尽可能购买公立医保覆盖您的就医需求，并且如果您出于经济问题考虑，部分医保公司会根据现实情况和奖学金等方面的考虑减免部分费用。

更加细化的保险方面的信息请参考保险细化指南。

<font color=red>请您千万不要使用递签所用的保险作为您的日常保险使用。这是对自身身体健康和经济问题的漠视</font>

### 私立医保

私立医保即字面含以上的，私人公司所开设的保险服务。通常疾病覆盖面较窄，并且大部分的保险套餐将需要您首先自行垫付医药费并将结算单据交付医保公司核实后将报销费用打还给您的私人账户。

::: {.callout-tip}
# 提示

有意思的是，德国的部分诊所仅接待私人医保覆盖的患者。

:::

## 日常就医

如您有就医需求，但是暂时不清楚您的具体病情如何以及不舒服的位置在哪，请向离您最近的家庭医生（Hausarzt）处报告。德国的家庭医生负责一级分诊，也就是帮助您进行初步诊断，若并不严重将初步治疗若需要后续治疗将转诊至二级分诊，也就是向您指定的二级医生（Krankenarzt）进行治疗。


::: {.callout-tip}
# 什么是转诊？我为什么需要转诊？

部分的德国专科诊所（也就是普遍意义上的专科门诊）需要您出示转诊单，也就überweisungsschein。换句话说，若您初次拜访且没有该证明，您可能无法获得预约或者治疗
:::

您可以通过地图/导航/搜索引擎等途径搜索家庭医生并取得联系。在这个环节，您应该将距离和地点等信息纳入考量，而将评分等作为第二位参考（当然如果评分过于离谱，则也应该慎重对待这类诊所）

若您初步判断后有明确的指征认为您清楚身体的哪个部分不舒服，您此时可以考虑专科门诊。专科门诊的分布一般较为分散且可能数量较少。同样可以在地图/导航/搜索引擎中搜索该科室的诊所分布并通过电话取得联系

::: {.callout-tip}
# 小提示

1. 一些小科室可能实际上属于一些大科室之下，因此若您发现市区没有该科室，可能是查询词不对，请放大搜索范围
2. 在这点上，您可以尝试使用AI帮您辅助分诊，确认大致的科室范围，然后联系相关医生/诊所
:::

## 紧急就医

虽然德国的诊所通常实行预约制，但是这不代表您无法在紧急情况获得帮助。如果突发不适，您可以尝试直接前往家庭医生的诊所并明确告知前台目前的身体状况，并请求一个Notfall Termin。通常，您可以被前台接纳并被加入等待位。但是等待时间将根据当天的人流量决定。通常这可能持续数个小时或整个半天。

如果您的身体状况已经不支持您前往户外，此时您应该拨打116 117获得专业帮助。该电话为紧急医疗求助热线，适用于您在尚未危及生命的情况下获得快速的第一支持。

当您认为该情况已经有概率危及到了您的生命，或者您有部分基础/慢性病，请不要犹豫立刻拨打112求助与医疗急救。

::: {.callout-tip}
# 小提示

虽然前文提到一般的医院基本不提供门诊服务，但是急诊肯定是开放的，如果您的位置附近刚好有急诊中心，条件允许情况下也可以去急诊寻求帮助

同样地，急诊有别于门诊，分诊护士将会快速根据病情严重程度安排就诊顺序，而非先后顺序，您需要耐心等待

:::

## 药品和药店

德国实行严格的医药分离制度，因此您无法在诊所/医院购买药品。但是通常药店（Apotheke）会紧挨着大部分诊所，您可以在离开诊所的时候直接前往并购买药品。通常，您会需要为每张处方单一次性支付10Euro的处方费用。

### 处方

德国的药品处方大致分为五种颜色。本文撰写时间点，已经有大部分药店和诊所实现了共享处方，您只需要在药店处出示您的医保卡，处方将自动和药店共享。

#### 粉红色/红色处方

用于开具由法定医疗保险公司报销的处方药。

医疗保险处方必须在签发之日起一个月内兑换。

#### 蓝色处方/白色处方

该处方类为私人处方。并非只有拥有私人医疗保险的人从医生那里获得私人处方。如果药品需要处方，但不在法定医疗保险的福利目录内，则拥有法定医疗保险的人也可以获得私人处方。

如果开具非处方药，则您还会收到私人处方。 然后，您必须自己为此付费。 如果您的医生没有获得医疗保险的许可，那么他只会开具私人处方。

私人处方自签发之日起三个月内有效。

#### 绿色处方

绿色处方包含医生对非处方药的建议。 它无限期有效，医疗保险不包括药品费用。

#### 黄色处方

在黄色处方上规定了受麻醉品法约束的高效物质，例如某些止痛药（阿片类药品）。 出于安全原因，这些所谓的BTM处方都有编号，有效期仅为7 天。

### 保健品

日用保健品和部分调理用品（也就是德国中药）可以在药妆店内购买。该品类药物通常作为膳食补给或者亚健康调理等非医疗需求出售，因此需要自费

### 疫苗

德国打疫苗打的挺狠的，并且医保公司会鼓励您施打疫苗以防止潜在的疾病威胁。

疫苗接种流程其实非常简单：

1. 前往家庭医生处，告知您需要接种什么疫苗，并预约接种时间
   1. 若您的接种时间为几日后，笔者建议您不要提前开药后自行保管，以免疫苗污染/失效
2. 于接种时间前往开药后带至家庭医生处接种
3. 将接种证明/小票/购买凭证等材料保存好后向医保公司报销。

#### 推荐的疫苗？

事实上如果您从小全程跟随中华人民共和国国家卫生健康委员会的要求接种疫苗，您只需要关注这几类疫苗的接种状况，并按需施打

1. 破伤风疫苗（百白破）：
   1. 通常需要重新接种的疫苗为破伤风。根据资料，破伤风疫苗的推荐加强周期是每十年。具体可咨询您的医生
2. HPV疫苗
   1. 作为预防恶性肿瘤的有效手段，可以考虑接种九价HPV疫苗
3. 蜱虫疫苗
   1. 虽然国内对于该疫苗的关注度较低，但是在德国，您可能会遇到蜱虫问题。如果您本身是过敏体制或发现了蜱虫侵扰问题，请和家庭医生取得联系并考虑这个疫苗
4. 流感疫苗
   1. 流感疫苗通常也可以被您的医保公司报销。如果您的流感症状通常严重且持续，并且本身有部分基础疾病，请咨询家庭医生，并接种流感疫苗
::: {.callout-tip}
# 小提示

流感不是小感冒，千万注意身体健康
:::
