# 延签，落户与外管局

欢迎来到萨尔！

<font color=red>在阅读本章前请您一定牢记：您的个人身份证件，包括不限于护照（旅行证），居留卡，身份证等，是您在德国（外国）能证明您身份的唯一文件，并且包含和您个人相关的信息。因此您绝对不应该将这些文件分享（无论是实体还是照片）给任何第三方，即使是熟人/朋友。</font>

您估计已经从各个现代社交媒体上获悉了部分关于德国行政效率的小故事。在此，我们能够和您确认的是，这些轶事可能大部分都是真的。因此，如果您已经成功安顿下来并准备开始您的生活，请确认您的行政相关材料是否完备，合理。在此，您需要首先确认几份非常重要的文书：

1. 落户证明，也称为Anmeldung/Anmeldungsbestaetigung
2. 居留权，也称为Aufenthaltserlaubnis
3. 税号登记，也称为Steuer-ID
4. ---

## 如何办理落户证明（Anmeldung）

Anmeldung 就像您在德国生活的“启动键”，是打开各种社会服务（如银行、健保、签证续签等）的第一步。

### 办理时机

理论上，您在抵达萨尔布吕肯后**两周内**必须完成落户登记。但是这个时间并不是绝对的，只需要尽快即可。

### 办理地点

萨尔布吕肯市政厅（*Bürgeramt*），也叫居民登记办公室（*Einwohnermeldeamt*）。

### 所需材料

- 护照或有效身份证件
- 房东出具的入住确认（*Wohnungsgeberbestätigung*）

### 流程

1. 请前往萨尔布吕肯市市政厅官网[搬迁与登记事务](https://www.saarbruecken.de/rathaus/buergerservice/umzug_und_meldeangelegenheiten)
2. 查看和您对应的登记事务和所需文件，准备相关文件
3. 备妥后，访问萨尔预约分发地址[就近预约](https://terminvergabe.saarbruecken.de/)
4. 预约成功后到现场办理落户手续
   
::: {.callout-tip}
# 提示

请一定保管好该证明，同时有条件情况下请扫描为电子版后异地备份
:::

## 居留许可

请注意，由于众所周知的原因，请务必在签证到期时间临近前，尽早考虑和ZAB取得联系！

您的贴纸签通常有效期只有3个月。因此，非欧盟国家的学生通常需在德国境内申请或延长学生居留许可。

### 首次申请所需材料包括但不限于：

- 完整填写的居留卡申请表
- 有效护照及签证页复印件
- 生物识别照片（符合护照标准）
  - 该规定目前有变化，截至修改日期，要求为在受认可的线下店铺内使用特定设备采集生物识别照片，而不必自己携带照片前往外管局
- 注册证明（*Immatrikulationsbescheinigung*）
- 财力证明（如银行存款、奖学金证明）
  - 该规定目前有变化，截至修改日期，要求为非雇员，非职员/hiwi学生需要强制出示/办妥保证金账户（Sperrkonto）
- 健康保险证明（*Krankenversicherung*）
- 落户证明（Anmeldung）

###  办理方式

1. 通过邮件、电话或线下预约外管局（*Ausländerbehörde*）
   1. 萨尔布吕肯所属为[Lebach办事中心](https://www.saarland.de/lava/DE/home/Abteilungen/Abteilung2)
2. 准备所有材料，并在给定的时间抵达外管局
   1. 请携带约100欧元的现金作为制卡费。
3. 提交所有材料并等待审理结果
4. 获批后领取实体居留卡/（*eAT*）

::: {.callout-tip}
# 我何时能收到我的居留卡？

1. 该项目完全取决于您的签证官工作效率和联邦印刷局的工作效率
2. 制卡流程可能持续数个月
3. 如果您的卡片有一定的紧迫性，请考虑在和签证官面谈时提出您需要加速流程express
   1. 该服务需要额外收取35欧元的费用
:::

## 居留延签（Verlängerung des Aufenthaltstitels）

延长您的居留卡/居留权

###  延签流程

1. 在许可到期前 6–8 周预约外管局
2. 准备并提交更新后的财力和学籍证明
3. 如首次一样缴费、采集指纹、等待制卡