# 落地交通

本指南团队建议您在选择您的落地机场时优先考虑法兰克福机场（FRA）。该机场与萨尔州的火车线路方便快捷，且能够帮助您规避在初次抵达德国时由于暂时不熟悉德国火车规则而产生的麻烦。

## 由您的落地机场机场至萨尔布吕肯中央火车站

下列指南将以您购买了抵达法兰克福机场的机票为例，以帮助您了解如何到达您的目的地。其余目的地您可同样使用该流程购买火车票。下面我们描述了普遍适用的购票流程

### 火车方式

::: {.callout-tip}

# 注意

- 德国铁路的所有快速火车票均参与市场竞争，即： 提前购买、选择非热门时段会降低票价，因此您需要提前规划您的行程。
- 德国慢速铁路火车普遍不提供座位预定服务。
- 如您乘坐快速铁路火车希望提前预定座位，需要额外购买此服务。
   - 如未预定，空余的座位遵循先到先得的原则（请注意座位上电子显示屏的标记，查看此行车区间是否有人已预定该座位）。
:::

我们以慢速火车（RE/RB）为例：


1. 首先您需要前往[德国铁路官网](bahn.de)，或者备用[英语站](https://int.bahn.de/en?dbkanal_007=sprachauswahl-en)
   -. 该网站使用流程清晰简单，输入您的始发站和目的地，并选择日期和出发时间，最后设置您的个人信息（年龄）点击搜索即可。
2. 您可以在大致出发前一个月至两周的区间内考虑购买德国的火车票。
   1. 若您已经激活您的学期票且当前政策依然为“学期票为全德国票”，您则不需要购买慢速火车车票
   2. 若您暂未激活学期票，您需要购买全程车票（学期票相关内容请参见申请您的学期票章节内容）
3. 以法兰克福机场为例，您的出发地为Frankfurt(M) Flughafen Regionalbf。请注意括号中的字母为M
4. 在您落地后请根据导航前往该火车站。
   1. 若您于T1航站楼落地，您只需根据箭头指示前往火车站即可
   2. 若您于T2航站楼落地，您需要通过机场摆渡铁路/摆渡公交先抵达T1航站楼后乘坐火车。
5. 当您抵达火车站楼内，请首先确认您的火车出发站台是几号。该站台号通常在Gl（德语Gleis缩写）或pl（platform缩写）后。
6. 确认好站台号后根据指示前往相应站台等待火车
7. 请在上车前再次核对您的车次，终到站。

若您购买快速火车（ICE/EC/IC/TGV（法国铁路）），您需要前往Frankfurt(M) Flughafen fernbf。除此之外流程一致

::: {.callout-tip}

# Tip

慢速火车没有专门放置大件行李的设施。在列车拥挤时，可以尝试将行李箱放置在座位底下，或两排方向相反的座椅靠背中间。快速火车通常会有大件行李架。
:::

### 乘坐包车/计程车前往您的住处

乘坐计程车是一个值得推荐的方式，尤其是您如果是第一次抵达德国，该方式有助于避免火车晚点/延误等不可抗力导致的任何潜在问题。

如您有需求，可以访问来自萨尔市市政府提供的部分联系方式：[计程车](https://www.saarbruecken.de/leben_in_saarbruecken/einkaufen/parken/taxistaende)

::: {.callout-tip}
# 谨慎

- 请尽可能避免与完全陌生的人拼车
- 不要相信可疑小广告，广告来源包括不限于任何社交媒体/搜索引擎广告
- 和司机/约车服务中心彻底谈妥价格
- 如有必要请规律向您的亲人报告具体位置
  - 或者打开地图软件跟踪自己的位置
:::

## 由萨尔布吕肯中央火车站前往您的住所

请您从Ausgang Stadt/exit city方向离开火车站，或者根据导航描述前往新城开发区。在[Saarfahrplan](https://saarvv.de/fahrplan/fahrplanauskunft/)以及附属App上确认您的车号和终到站方向，前往公交站台。若您不确定您的站牌是几号，请寻找火车站前方购物中心一楼麦当劳，麦当劳前方公交车站为常用开往市区的班车。若方向相反，请前往对向车道观察站牌。
