on:
  push:
    branches:
      - main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish (English)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: content
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Render and Publish (Chinese)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: content_zh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
